[tool.ruff]
line-length = 100
target-version = "py311"

# Either exclude the whole legacy file:
exclude = ["streamlit_app.py"]

# Or, if you prefer to lint it but ignore the noisy rules, use per-file ignores:
# [tool.ruff.per-file-ignores]
# "streamlit_app.py" = ["E701", "E702", "E402", "F821"]

[tool.black]
line-length = 100
target-version = ["py311"]
